---
title: SoCal Elite Physical Therapy
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  team-members:
    title: Team Members
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/:categories/:title"
    description: ''
    featured-image: ''
    alt-tag: ''
url: https://www.socalelitephysicaltherapy.com
baseurl:
email: admin@socalelitephysicaltherapy.com
description: Welcome to Socal Elite Physical Therapy. Providing physical therapy in
  Irvine, CA. Visit us today to schedule your appointment!
logo: img/logos/socal-elite-logo-white.png
social:
- title: facebook
  url: https://www.facebook.com/SoCalElitePhysicalTherapy/
- title: instagram
  url: https://instagram.com/socalelitephysicaltherapy/
- title: yelp
  url: https://www.yelp.com/biz/socal-elite-physical-therapy-irvine
address:
- line: 12 Mauchly, Suite P
- line: Irvine, CA 92075
markdown: kramdown
permalink: pretty
include:
- _redirects
