---
title: SoCal Elite Physical Therapy
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  team-members:
    title: Team Members
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/:categories/:title"
    description: ''
    featured-image: ''
    alt-tag: ''
url: https://www.socalelitephysicaltherapy.com
baseurl:
email: admin@socalelitephysicaltherapy.com
description: Welcome to Socal Elite Physical Therapy. Providing physical therapy in Irvine, CA. Visit us today to schedule your appointment!
logo: img/logos/rise-main-logo.png
social:
- title: twitter
  url: http://twitter.com/
- title: facebook
  url: https://www.facebook.com/
- title: instagram
  url: https://instagram.com/
- title: linkedin
  url: https://www.linkedin.com/
address:
- line: 12 Mauchly, Suite P
- line: Irvine, CA 92075
markdown: kramdown
permalink: pretty
include:
- _redirects
